ext/duckdb/duckdb.c, ext/duckdb/prepared_statement.c, ext/duckdb/prepared_statement.h, ext/duckdb/ruby-duckdb.h, test/duckdb_test/prepared_statement_test.rb
this is step 1 of supporting prepared statement
=> add prepared statement class

ext/duckdb/connection.c, ext/duckdb/connection.h, ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
This is 2nd step of supporting prepared statement
=> add DuckDB::PreparedStatement#initialize

ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
3rd step of supporting prepared statemant
=> add DuckerDB::PreparedStatement#execute

ext/duckdb/prepared_statement.c, ext/duckdb/prepared_statement.h, test/duckdb_test/prepared_statement_test.rb
support prepared statement step 4.
=> add DuckDB::PreparedStatement#nparams

ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
supporting prepared statement step 5
=> add DuckDB::PreparedStatement#bind_varchar

ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
supporting prepared statement. step 6
=> add DuckDB::PreparedStatement#bind_boolean

ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
supporting prepared statement. step 7
=> add DuckDB::PreparedStatement#bind_float/bind_double

.travis.yml, Gemfile.lock, duckdb.gemspec
=> setup travis ci

.travis.yml
adding duckdb version 0.1.3 to travis CI test
=> add duckdb version 0.1.3

ext/duckdb/database.c, lib/duckdb/database.rb, test/duckdb_test/database_test.rb
this is first step so that DuckDB::Database#open can accept block.
=> refactoring DuckDB::Database#open

CHANGELOG.md, ext/duckdb/connection.c, ext/duckdb/connection.h, ext/duckdb/database.c, ext/duckdb/database.h, ext/duckdb/error.c, ext/duckdb/error.h, ext/duckdb/ruby-duckdb.h
fix to build failure in MAC OS/X
=> fix to build failure in MAC OS/X

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .travis.yml, CHANGELOG.md, Gemfile.lock
=> support ruby 3.0.0

test/test_helper.rb
from https://alanwu.space/post/check-compaction/
=> GC.verify_compaction_referencies test

CHANGELOG.md, ext/duckdb/extconf.rb, ext/duckdb/prepared_statement.c
this PR is to fix #170
The fixing some test failures with duckdb 0.2.9 will be fixed on another PR.
=> fix build with duckdb 029

test/duckdb_test/appender_test.rb
These errors will be fixed other PRs.
=> avoid some appender errors with duckdb 0.2.9 or later.

ext/duckdb/appender.c, ext/duckdb/extconf.rb, test/duckdb_test/appender_test.rb
=> add DuckDB::Appender#_append_date

.github/workflows/test_on_ubuntu.yml, .travis.yml
=> Bump to 0.2.9 ci

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml, .travis.yml
=> drop ruby 2.5.8 from CI

ext/duckdb/appender.c, ext/duckdb/extconf.rb, test/duckdb_test/appender_test.rb
=> add Appender#_append_interval

ext/duckdb/appender.c, ext/duckdb/extconf.rb, test/duckdb_test/appender_test.rb
=> add Appender#_append_time private method

ext/duckdb/appender.c, ext/duckdb/extconf.rb, test/duckdb_test/appender_test.rb
=> add Appender#_append_timestamp private method

ext/duckdb/appender.c, ext/duckdb/extconf.rb, test/duckdb_test/appender_test.rb
=> add Appender#_append_hugeint

CHANGELOG.md, lib/duckdb/appender.rb, test/duckdb_test/appender_test.rb
=> implement Append#append_hugeint

.github/workflows/test_on_macos.yml
=> enable multi duckdb version on MacOS CI

.github/workflows/test_on_windows.yml, README.md, test/duckdb_test/database_test.rb
=> Fix rake test on windows

CHANGELOG.md, ext/duckdb/result.c, test/duckdb_test/result_test.rb
=> add DuckDB::Result#rows_changed

test/duckdb_test/appender_test.rb
=> fix rake test failure

CHANGELOG.md, lib/duckdb/appender.rb, test/duckdb_test/appender_test.rb
Resolve https://github.com/suketa/ruby-duckdb/issues/172
=> Add public method append_date

lib/duckdb/appender.rb, test/duckdb_test/appender_test.rb
=> Append#append_date accepts argument which can be parsed as Date/Time

lib/duckdb/appender.rb, test/duckdb_test/appender_test.rb
=> Appender#append_time accept Time conversionable argument.

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml, CHANGELOG.md
=> CI uses duckdb v0.3.0

lib/duckdb/appender.rb, test/duckdb_test/appender_test.rb
=> Appender#append_time accept Time or Date conversionable argument.

.github/workflows/test_on_macos.yml
=> fix macos CI

lib/duckdb/prepared_statement.rb, test/duckdb_test/prepared_statement_test.rb
=> Add bind_date

lib/duckdb.rb, lib/duckdb/appender.rb, lib/duckdb/converter.rb, lib/duckdb/prepared_statement.rb, test/duckdb_test/prepared_statement_test.rb
=> add bind_interval

lib/duckdb/prepared_statement.rb, test/duckdb_test/prepared_statement_test.rb
This solves issue #250. Tests are still pending, and will be pushed soon.
=> Add bind_time to PreparedStatement

README.md
Has instructions for DuckDB setup in Linux. Fixes #268.
=> Added prerequisite configuration (Linux)

.github/workflows/test_on_windows.yml, lib/duckdb/prepared_statement.rb, test/duckdb_test/prepared_statement_test.rb
=> fix bind_time error

ext/duckdb/extconf.rb, ext/duckdb/prepared_statement.c
=> remove duckdb_nparams check

ext/duckdb/extconf.rb, ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
=> refactoring remove check bind_time

ext/duckdb/extconf.rb, ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
=> remove bind_date check

ext/duckdb/column.c, ext/duckdb/column.h, ext/duckdb/duckdb.c, ext/duckdb/result.c, ext/duckdb/ruby-duckdb.h, test/duckdb_test/column_test.rb, test/duckdb_test/result_test.rb
This solved #168.
Add result#columns and column class.
Would you mind looking at this PR?
=> [#168]Add DuckDB::Result#columns

ext/duckdb/extconf.rb, ext/duckdb/result.c
This should solve issue #301. Not sure if I have to remove `#ifdef HAVE_DUCKDB_FREE`  from `result.c`.
=> Remove checking duckdb_free

ext/duckdb/appender.c, ext/duckdb/appender.h, ext/duckdb/duckdb.c, ext/duckdb/extconf.rb, ext/duckdb/ruby-duckdb.h
This should solve issue #302. I am not sure about removing `duckdb_appender_create` in line 78 of `appender.c`, so it would be better that I do not touch that.
=> Remove checking duckdb_appender_create

lib/duckdb/appender.rb
DuckDB::Appender class is always defined now.
=> refactoring: DuckDB::Appender class check is removed from lib/duckdb/appender.rb.

ext/duckdb/appender.c, ext/duckdb/extconf.rb
=> uncheck duckdb_append_timestamp

ext/duckdb/appender.c, ext/duckdb/extconf.rb
=> remove duckdb_append_time check from extconf.rb (#295)

ext/duckdb/appender.c, ext/duckdb/extconf.rb
refs https://github.com/suketa/ruby-duckdb/issues/296
=> remove duckdb_append_interval check from extconf.rb(#296)

CHANGELOG.md, ext/duckdb/result.c, lib/duckdb/result.rb, test/duckdb_test/result_test.rb
=> add DuckDB::Result#column_count, column_size (#165)

ext/duckdb/appender.c, ext/duckdb/extconf.rb, ext/duckdb/util.c, ext/duckdb/util.h, test/duckdb_test/appender_test.rb
=> remove duckdb_append_date check from extconf.rb

ext/duckdb/extconf.rb, ext/duckdb/prepared_statement.c
=> refactoring. remove duckdb_prepare_error check.

ext/duckdb/config.c, ext/duckdb/config.h, ext/duckdb/duckdb.c, ext/duckdb/extconf.rb, ext/duckdb/ruby-duckdb.h, test/duckdb_test/config_test.rb
=> remove duckdb_config_create check (#300)

test/duckdb_test/enum_test.rb
=> add NG test enum column

test/duckdb_test/column_test.rb
=> list column test

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml, CHANGELOG.md
changed duckDB version on CI.
and added change log.
=> bump duckdb v0.6.0 on CI

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml
=> use actions/cache@v3 (#412)

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml
This PR contains bump duckdb to 0.6.1 on CI
=> bump duckdb to 0.6.1 on CI

CHANGELOG.md, ext/duckdb/extconf.rb
=> fix build error on M1 MacOS

ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
=> add _bind_hugeint

test/test_helper.rb
=> fix GC.verify_compaction_references warning

CHANGELOG.md, ext/duckdb/extconf.rb
=> drop duckdb <= 0.4.0

ext/duckdb/result.c, test/duckdb_test/result_test.rb
=> add DuckDB::Result#_to_string_internal

ext/duckdb/result.c, test/duckdb_test/result_hugeint_internal_test.rb, test/duckdb_test/result_to_decimal_internal_test.rb
=> add Decimal#__to_decimal_internal

CHANGELOG.md, lib/duckdb.rb, lib/duckdb/library_version.rb, lib/duckdb/version.rb, test/duckdb_test.rb
Add DuckDB::LIBRARY_VERSION.
and added change log.
=> Add duck db library version

.github/workflows/test_on_windows.yml
This reverts commit 36ac232b642ddf50c7a68f5052decebbcae5ab99.
Now windows ci failures are fixed.
=> Revert "windows CI test (#455)"

test/duckdb_test/prepared_statement_test.rb
=> chore: remove unused variable

CONTRIBUTION.md, Dockerfile, Gemfile.lock, docker-compose.yml
Add docker environment to make it easier to start to contribute
=> feat: introduce Docker

ext/duckdb/prepared_statement.c, ext/duckdb/result.c
fix conversion i64 numbers from C to Ruby, Ruby to C.
=> fix conversion numbers

Dockerfile, getduckdb.sh
=> fix docker compose build error on M1 Mac

test/duckdb_test/enum_test.rb
=> fix enum test

.github/workflows/test_on_ubuntu.yml, Gemfile, Gemfile.lock, Rakefile
=> try to check memory-leak

CHANGELOG.md, ext/duckdb/result.c, test/duckdb_test/result_chunk_each_test.rb
=> support UTINYINT

benchmark/get_converter_module_ips.rb, ext/duckdb/converter.h, ext/duckdb/conveter.c, ext/duckdb/duckdb.c, ext/duckdb/result.c, ext/duckdb/ruby-duckdb.h
use mDuckDBConverter to call Converter module function from C.
=> define mDuckDBConveter value.

CHANGELOG.md, Dockerfile, Gemfile.lock, lib/duckdb/version.rb
=> prepare releasing v0.9.0

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml
use Ruby 3.3.0-rc1 in CI test.
=> CI test with Ruby 3.3.0-rc1.

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml, CHANGELOG.md, duckdb.gemspec
This reverts commit a99bfe2de49c3a633613a9ae500a1a02adc70bb3.
=> Revert "drop Ruby 2.7. (#575)"

CHANGELOG.md, Gemfile.lock, duckdb.gemspec
=> fix bigdecimal warning.

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml, CHANGELOG.md, ext/duckdb/connection.c, ext/duckdb/extconf.rb, ext/duckdb/ruby-duckdb.h, lib/duckdb/column.rb, lib/duckdb/result.rb, test/duckdb_test/appender_test.rb, test/duckdb_test/prepared_statement_test.rb, test/duckdb_test/result_test.rb
=> fix build error with duckdb v0.10.0.

.github/workflows/test_on_macos.yml, .github/workflows/test_on_ubuntu.yml, .github/workflows/test_on_windows.yml, lib/duckdb/column.rb, lib/duckdb/result.rb, test/duckdb_test/result_test.rb
fix failures because of https://github.com/duckdb/duckdb/pull/10649
=> Fix failures with duckdb v0.10.1

CHANGELOG.md, ext/duckdb/extconf.rb
=> fix error using binding with name.

ext/duckdb/result.c, test/duckdb_test/result_chunk_each_test.rb
- DuckDB::Result#chunk_each.
- DuckDB::Result#_chunk_stream.
=> use rb_ensure to call duckdb_destroy_data_chunk after yield.

CHANGELOG.md, ext/duckdb/result.c, test/duckdb_test/result_chunk_each_test.rb
=> support fetch the value from UHUGEINT type column.

CHANGELOG.md, ext/duckdb/appender.c, lib/duckdb/appender.rb, test/duckdb_test/appender_test.rb
=> Add append uhugeint

CHANGELOG.md, ext/duckdb/result.c, test/duckdb_test/result_chunk_each_test.rb, test/duckdb_test/result_list_test.rb
=> DuckDB::Result supports LIST column type.

CHANGELOG.md, test/duckdb_test/result_list_test.rb
=> add more test for LIST column type.

test/duckdb_test/result_chunk_each_test.rb
=> fix STRUCT test in result_chunk_each_test

ext/duckdb/result.c, test/duckdb_test/result_bit_test.rb, test/duckdb_test/result_chunk_each_test.rb
=> DuckDB::Result supports BIT column type

ext/duckdb/duckdb.c, ext/duckdb/result.c, ext/duckdb/ruby-duckdb.h, test/duckdb_test/result_chunk_each_test.rb
=> check date is infinite.

ext/duckdb/result.c, lib/duckdb.rb, lib/duckdb/converter.rb, lib/duckdb/infinity.rb, test/duckdb_test/result_chunk_each_test.rb
refs #692
- support infinity for TIMESTAMP_S column.
- refactoring.
=> support infinity for timestamp_s column

CHANGELOG.md, ext/duckdb/result.c, lib/duckdb/result.rb, test/duckdb_test/result_test.rb
=> Duckdb result return type

CHANGELOG.md, ext/duckdb/result.c, lib/duckdb/result.rb, test/duckdb_test/result_test.rb
=> Duckdb result statement type

CHANGELOG.md, ext/duckdb/prepared_statement.c, lib/duckdb/converter.rb, lib/duckdb/converter/int_to_sym.rb, lib/duckdb/prepared_statement.rb, lib/duckdb/result.rb, test/duckdb_test/prepared_statement_test.rb, test/test_helper.rb
=> add DuckDB::PreparedStatement#statement_type.

CHANGELOG.md, ext/duckdb/prepared_statement.c, test/duckdb_test/prepared_statement_test.rb
=> add DuckDB::PreparedStatement#clear_bindings.

test/duckdb_test/pending_result_test.rb
=> try to fix flaky test.

test/duckdb_test/enum_test.rb
- fix here document style.
- remove if check.
- already fixed memory leak.
=> refactoring. enum_test.rb

test/duckdb_test/column_test.rb
fix GH-336
Add a test about struct column.
ref: https://duckdb.org/docs/sql/data_types/struct.html
=> struct column test

CHANGELOG.md, lib/duckdb/connection.rb
- DuckDB::Connection#prepared_statement accepts block.
- refactoring methods to use prepared_statement with block.
=> DuckDB::Connection#prepared_statement accepts block.

test/duckdb_test/result_time_tz_test.rb
Ignore summer time to pass test always.
=> fix time zone test.

CHANGELOG.md, ext/duckdb/prepared_statement.c, lib/duckdb/connection.rb, test/duckdb_test/connection_execute_multiple_sql_test.rb, test/duckdb_test/connection_test.rb, test/duckdb_test/database_test.rb, test/duckdb_test/extracted_statements_test.rb
=> DuckDB::Connection#query accepts multiple SQL statement.

test/duckdb_test/column_test.rb
Add column types test for:
#342  - Json column
#341 - UUID Column
#340 - Map column
=> Add uuid, json and map column test

CHANGELOG.md, ext/duckdb/appender.c, test/duckdb_test/appender_test.rb
=> add DuckDB::Appender#append_default

ext/duckdb/database.c
undocument internal methods in DuckDB::Database.
=> fix DuckDB::Database document

.github/workflows/test_on_macos.yml, .github/workflows/test_on_windows.yml
- enable head on Mac/OSX.
- bump ruby on Windows.
=> try to bump ruby on CI

CHANGELOG.md, ext/duckdb/appender.c, lib/duckdb/appender.rb
I don't know how to add faild case test.
=> get error message from duckdb when DuckDB::Appender#append_bool failed.

lib/duckdb/appender.rb
=> fix appender rdoc.

ext/duckdb/prepared_statement.c
add private method _bind_uhugeint to PreparedStatement.
refs #696
=> add PreparedStatement#_bind_uhugeint.
