test/duckdb_test/prepared_statement_test.rb

DuckDB::PreparedStatement#bind_null is not defined with DuckDB
version <= 0.1.1. So skip test_bind_null if bind_null is not defined.

skip test_bind_null if bind_null method is not defined

---

lib/duckdb/appender.rb
lib/duckdb/prepared_statement.rb
test/duckdb_test/appender_test.rb
test/duckdb_test/prepared_statement_test.rb

- Replace `rb_raise` with `raise` in ruby files
- Write tests for raise cases
- Using `rb_raise` causes `undefined method` exception

Replace 'rb_raise' with 'raise' in rb files

---

lib/duckdb/prepared_statement.rb
test/duckdb_test/prepared_statement_test.rb

remove bind_null implemented check

---

README.md
ext/duckdb/column.c
ext/duckdb/config.c
ext/duckdb/result.c
test/duckdb_test/column_test.rb
test/duckdb_test/enum_test.rb
test/duckdb_test/result_test.rb

Changes all occurrences of `rb_str_new2` to `rb_utf8_str_new_cstr` in order to construct all Ruby strings with UTF-8 encoding. This affects column names, values for `VARCHAR` and `ENUM` types and config attributes.

use UTF-8 encoding when constructing strings

---

CHANGELOG.md
ext/duckdb/result.c
test/duckdb_test/appender_test.rb
test/duckdb_test/result_test.rb

Fix the following bug
```ruby
con.execute('create table t (col boolean)')
con.execute('insert into t values(false)');
r = con.execute('select col from t')
r.first.first #=> expected false, but always true.
```

Fix reading from boolean column

---

.github/workflows/test_on_macos.yml
.github/workflows/test_on_ubuntu.yml

Changed preview version of Ruby(preview2->preview3).
This version was not yet supported on windows. (https://github.com/ruby/setup-ruby/tree/v1)

change ruby 3.2.0 preview3

---

ext/duckdb/result.c
test/duckdb_test/result_hugeint_internal_test.rb

rename method name for DuckDB::Result#_to_hugeint_internal Ruby method

rename DuckDB::Result#_to_hugeint_internal to DuckDB::Result#__to_hugeint_internal

---

ext/duckdb/extconf.rb

https://docs.ruby-lang.org/en/3.2/MakeMakefile.html#method-i-have_func
`func` is the first argument of `have_func` method
`rake build` result after change
```
root@cea3c125f267:~/ruby-duckdb# bundle exec rake build
cd tmp/x86_64-linux/duckdb_native/3.2.1
/usr/local/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/duckdb/extconf.rb
checking for duckdb.h... yes
checking for duckdb_pending_prepared() in duckdb... no
checking for duckdb_pending_prepared() in -lduckdb... yes
checking for duckdb_append_data_chunk() in duckdb.h... yes
checking for duckdb_value_string() in duckdb.h... yes
checking for duckdb_free() in duckdb.h... yes
creating Makefile
```

fix: have_func arguments order

---

Gemfile.lock

refs #478 
`bundler` version 2.5.0.dev comes with ruby head and the exception was raised.
add BUNDLED_WITH 2.4.8 into Gemfile.lock to fix this issue temporarily.

refs #478 temporaly fix for failing CI

---

.github/workflows/test_on_macos.yml
.github/workflows/test_on_ubuntu.yml
Gemfile
Gemfile.lock
benchmark/to_hugeint_ips.rb
benchmark/to_hugeint_profile.rb
lib/duckdb/result.rb

refs #443 
use `_to_hugeint_internal` to convert hugeint column value.
```
$ ruby benchmark/to_hugeint_ips.rb
Warming up --------------------------------------
_to_hugeint    72.649k i/100ms
_to_hugeint_internal   211.847k i/100ms
Calculating -------------------------------------
_to_hugeint    728.915k (± 0.3%) i/s -      3.705M in   5.083096s
_to_hugeint_internal      2.064M (± 1.4%) i/s -     10.381M in   5.029377s
```

use _to_hugeint_internal instead of _to_hugeint

---

CHANGELOG.md
benchmark/to_bigdecimal_ips.rb
lib/duckdb/result.rb
test/duckdb_test/result_to_decimal_test.rb

refs #470, #448
Benchmark
```
$ ruby benchmark/to_bigdecimal_ips.rb
Warming up --------------------------------------
_to_decimal    73.478k i/100ms
_to_decimal_internal   122.871k i/100ms
Calculating -------------------------------------
_to_decimal    705.637k (± 2.7%) i/s -      3.600M in   5.106288s
_to_decimal_internal      1.161M (± 2.4%) i/s -      5.898M in   5.084870s
```

implement DuckDB::Result#_to_decimal_internal

---

CHANGELOG.md
test/duckdb_test/config_test.rb

In duckdb >= 0.8.1, duckdb_set_config does not return error with invalid configuration key.
Instead, duckdb_open_ext returns error with configuration having invalid configuration.

fix DuckDB::Config.set_config error

---

CHANGELOG.md
ext/duckdb/result.c
lib/duckdb/converter.rb
lib/duckdb/result.rb
test/duckdb_test/result_chunk_each_test.rb

refactoring of #495.
add `DuckDB::Result#chunk_each` method.
It is only available with duckdb >= 0.8.0.
Set `DuckDB::Result.use_chunk_each` to true If you try to use chunk_each.
```ruby
DuckDB::Result.use_chunk_each = true
...
result = conn.query('SELECT * from TABLES');
result.each do # <= result.each works like as result.chunk_each
p row
end
```

Use chunk data for DuckDB::Result.

---

lib/duckdb/result.rb
test/duckdb_test/result_test.rb

`DuckDB::Result.new.each.to_a` causes segmentation fault.
`DuckDB::Result.new` should not be used.

fix segmentation fault when DuckDB::Result.new.each.to_a

---

CHANGELOG.md

Only adding for releases since 0.9. Also fixed subheadings.

Add timestamps to changelog

---

CHANGELOG.md
Gemfile.lock

nokogiri used for development ruby-duckdb only.

bundle update to bump nokogiri from 1.16.0 to 1.16.2

---

CHANGELOG.md
ext/duckdb/extracted_statements.c
test/duckdb_test/extracted_statements_test.rb

- raise error when `DuckDB::ExtractedStatements#new` is called with invalid SQL.
- add `DuckDB::ExtractedStatements#size`.

implement DuckDB::ExtractedStatements

---

lib/duckdb/result.rb
test/duckdb_test/appender_test.rb
test/duckdb_test/connection_test.rb
test/duckdb_test/enum_test.rb
test/duckdb_test/prepared_statement_test.rb
test/duckdb_test/result_chunk_each_test.rb
test/duckdb_test/result_test.rb

Some duckdb CAPI functions will be deprecated. So ruby-duckdb chunk_each_default is changed to true not to use deprecated CAPI.
There are some breaking changes.

use_chunk_each default is true

---

CHANGELOG.md
ext/duckdb/result.c
test/duckdb_test/result_struct_test.rb

support STRUCT column with DuckDB::Result

---

ext/duckdb/result.c

add unsupported column type of DuckDB:Result.

refactoring

---

test/duckdb_test/pending_result_test.rb

fix error when testing pending_result_test.rb only.

add require 'test_helper' 

---

CHANGELOG.md
lib/duckdb/connection.rb
test/duckdb_test/connection_test.rb

`DuckDB::Connection#prepare` is an alias of `DuckDB::Connection#prepared_statement`.

add `DuckDB::Connection#prepare`.

---

ext/duckdb/connection.c
test/duckdb_test/connection_test.rb

extconf.rb checks duckdb >= 0.10.0. So we don't need to write `#ifdef HAVE_DUCKDB_H_GE_V0_10_0`

remove #ifdef HAVE_DUCKDB_H_GE_V0_10_0.

---

lib/duckdb/converter/int_to_sym.rb

remove duckdb version check because dropping duckdb 0.10.x.

remove duckdb version check of DuckDB::Converter::IntoToSym

---

test/duckdb_test/prepared_statement_test.rb

ruby-duckdb supports only duckdb >= 1.0.0.
So, drop duckdb >= 0.10.0 check in PreparedStatement test.

drop duckdb 0.10.0 check

---

test/duckdb_test/result_test.rb

ruby-duckdb supports only duckdb >= 1.0.0.
So remove duckdb 0.10.0 check in DuckDB::Reslt test.

drop duckdb 0.10.0 check in Result test

---

lib/duckdb/converter.rb

- use `^=`.
- Converter is added `# :nodoc: all`.
- Converter class is for ruby-duckdb internal module.

refactoring Converter

---

CHANGELOG.md
ext/duckdb/prepared_statement.c
lib/duckdb/connection.rb

ensure to call DuckDB::PreparedStatement#destroy in:
- DuckDB::Connection#query
- DuckDB::Connection#async_query
- DuckDB::Connection#async_query_stream
related to #775, #781.

Add DuckDB::PreparedStatement#destroy

---

ext/duckdb/prepared_statement.c
test/duckdb_test/prepared_statement_test.rb

fix GH-#407
Implement DuckDB::PreparedStatement#_bind_decimal using duckdb_bind_decimal.
FYI: The following is the infromation of the function and type.
```cpp
duckdb_state duckdb_bind_decimal(
duckdb_prepared_statement prepared_statement,
idx_t param_idx,
duckdb_decimal val
);
typedef struct {
uint8_t width;
uint8_t scale;
duckdb_hugeint value;
} duckdb_decimal;
typedef struct {
uint64_t lower;
int64_t upper;
} duckdb_hugeint;
```
ref: https://duckdb.org/docs/api/c/api.html#duckdb_bind_decimal

add DuckDB::PreparedStatement#_bind_decimal

---

CHANGELOG.md
lib/duckdb/prepared_statement.rb
test/duckdb_test/prepared_statement_test.rb

You can write the followings
PreparedStatement.prepare(sql) do |stmt|
stmt.execute
end

add DuckDB::PreparedStatement#prepare

---

lib/duckdb/converter.rb
lib/duckdb/prepared_statement.rb
test/duckdb_test/prepared_statement_test.rb

fix GH-407
This change allows us to use `DuckDB::PreparedStatement#_bind_decimal` internally instead of `DuckDB::PreparedStatement#bind_varchar`.

add DuckDB::PreparedStatement#bind_decimal

---

.github/workflows/test_on_macos.yml

skip CI test because of the failure on head of ruby
https://github.com/suketa/ruby-duckdb/actions/runs/11866047410/job/33072199954?pr=805

skip temporary ruby head test on Mac CI.

---

test/duckdb_test/column_test.rb

This reverts commit 29badc5522b71a4cc22ccceac582290793086b38.
I don't know the reason why the following CI failed. And I can't fix it easily.
https://github.com/suketa/ruby-duckdb/actions/runs/11939362528/job/33279724957
So revert the commit temporarily.

Revert "Add uuid, json and map column test"

---

ext/duckdb/appender.c
ext/duckdb/blob.c
ext/duckdb/column.c
ext/duckdb/config.c
ext/duckdb/connection.c
ext/duckdb/database.c
ext/duckdb/error.c
ext/duckdb/extracted_statements.c
ext/duckdb/pending_result.c
ext/duckdb/prepared_statement.c
ext/duckdb/result.c

rdoc does not parse C files in some cases.
Add rb_define_module("DuckDB") to fix it.

make rdoc parse C files.

---

ext/duckdb/duckdb.c
ext/duckdb/logical_type.c
ext/duckdb/logical_type.h
ext/duckdb/ruby-duckdb.h
test/duckdb_test/logical_type_test.rb

GitHub: GH-690
This PR is the first step to support duckdb_logical_column_type C API. At the following PRs, we will implement it step by step.
In this PR, we adds `DuckDB::LogicalType` class which will handle duckdb_logical_column_type C API.

logical_type: define DuckDB::LogicalType class

---

CHANGELOG.md
ext/duckdb/appender.c
lib/duckdb/appender.rb
test/duckdb_test/appender_test.rb

- add 'DuckDB::Appender#error_message'.
- fix error message when DuckDB::Appender#flush failed.

add DuckDB::Appender#error_message

---

CHANGELOG.md
README.md
ext/duckdb/appender.c
lib/duckdb/appender.rb
lib/duckdb/interval.rb
test/duckdb_test/appender_test.rb

duckdb_appender_begin_row now only returns DuckDBSuccess and does nothing. The function exists because of backwards compatibility.
So DuckDB::Appender#begin_row returns self only.

DuckDB::Appender#begin_row returns self only

---

ext/duckdb/column.c
ext/duckdb/logical_type.c
ext/duckdb/logical_type.h
lib/duckdb/column.rb
test/duckdb_test/column_test.rb

refs: GH-690
In this PR, we add DuckDB::Column#logical_type, which returns the `DuckDB::LogicalType` instance corresponding to the column.
This is one of the steps for supporting duckdb_logical_column_type C API.

add DuckDB::Column#logical_type

---

test/duckdb_test/prepared_statement_test.rb

fix frozen_string_literal warnings with Ruby 3.4.1.

fix frozen_string_literal warning

---

CHANGELOG.md
ext/duckdb/appender.c
lib/duckdb/appender.rb
test/duckdb_test/appender_test.rb

try to retrieve error message from duckdb when close method failed.

fix error message of DuckDB::Appender#close

---

CHANGELOG.md
ext/duckdb/appender.c
lib/duckdb/appender.rb

I don't know how to add failed case of DuckDB::Appender#append_int8

retrieve error message from duckdb in DuckDB::Appender#append_int8

---

ext/duckdb/logical_type.c
test/duckdb_test/logical_type_test.rb

refs: GH-690
In this PR, we support interfaces for Decimal logical type in DuckDB::Column#logical_type about the following.
- [uint8_t duckdb_decimal_width(duckdb_logical_type type);](https://duckdb.org/docs/api/c/api.html#duckdb_decimal_width)
- [uint8_t duckdb_decimal_scale(duckdb_logical_type type);](https://duckdb.org/docs/api/c/api.html#duckdb_decimal_scale)
This is one of the steps for supporting duckdb_logical_column_type C API.

support interfaces for Decimal logical type in DuckDB::LogicalType

---

ext/duckdb/logical_type.c
lib/duckdb.rb
lib/duckdb/logical_type.rb
test/duckdb_test/logical_type_test.rb

refs: GH-690
In this PR, we add DuckDB::LogicalType#type, which returns logical type's type.
- [duckdb_type duckdb_get_type_id(duckdb_logical_type type);](https://duckdb.org/docs/api/c/api.html#duckdb_get_type_id)
This is one of the steps for supporting duckdb_logical_column_type C API.

add DuckDB::LogicalType#type
